travis:
  secure:
    BINSTAR_TOKEN: RUDVBk+zPrHc2ulzccGb8bshSgnWUY2Ig5EszRys+j3vRlcCputgP+n+p8z1/ujLVIlIdxfOYPFqpCX6Mt4vFUw8Qc2d8eAPLRc5istbFc95uBF0+4APB8zsDVMF11j9xdqE72mUy0NxmlPDfEcZ29s6lR/jpsqjLDMj4lPP82pG9oBbPmHWxz0r2AQldfSDRLPh4kbNJkw8Q9W8bvonNx1Qmw6iAoiCcV455nJgTnbJyCkbuxhta0I+DQLdjZVc6z3nJ8zjcB97QVx+ofLr7zvOoRSMYGtVHR8YDw3ulTyJt9/J9qrbxBum7G4vyEPPIfhc4cpIqfockyygze6ECWIu8QpqLBJfKcIwVd+HcHBjMSj3vsbDV2McrfqXVFJ1l29qeMCf7U0/Xx24+bvFpVdUlwlYqVvbT8ngsqzJKUqMQ8oFCoTASTsfEg67k6GRMVuDteorcosiBT3jQJ7gY5UAtdKcjuHcvBy+CaoEknGtT98jw8xDeJp4WOwVlUi/FDpaFNOuvbcjjYKGJIRT67paEt7ABgDtmhb7YeeX260wnEW/3XSChTnENTraZVbFLa5RZnOSHxByZXxnP8yOWyCAOZ4bxPt65UvPEKvopPQMkgrPjIj0+Fr6W18G/vfh09fYhUYLf+aNQbR9dARdYmbTWh2c7u9kcCkYGwdBKZs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
